export const employeesList = [
  {
    firstname: 'Flash',
    lastname: 'McQueen',
    dateOfBirth: '14/03/2006',
    startdate: '14/06/2006',
    departement: 'Les Bagnoles',
    street: 'route 66',
    city: 'Radiator Springs',
    state: 'AL',
    zipcode: '34567',
  },
  {
    firstname: 'Buzz',
    lastname: 'Lightyear',
    dateOfBirth: '22/11/1995',
    startdate: '24/01/2022',
    departement: 'Planete inconnu',
    street: 'route des étoiles',
    city: 'Vers l infini et au-delà',
    state: 'AZ',
    zipcode: '57421',
  },
  {
    firstname: 'Robert',
    lastname: 'Parr',
    dateOfBirth: '05/11/2004',
    startdate: '12/04/2017',
    departement: 'ville des super-heros',
    street: 'rue des indestructibles',
    city: 'Metroville',
    state: 'AR',
    zipcode: '76524',
  },
  {
    firstname: 'Remy',
    lastname: 'Ratatouille',
    dateOfBirth: '29/06/2017',
    startdate: '07/07/2020',
    departement: 'Paris',
    street: 'rue Auguste Gusteau',
    city: 'Paris',
    state: 'CO',
    zipcode: '75000',
  },
  {
    firstname: 'Baymax',
    lastname: 'Baymax',
    dateOfBirth: '07/11/2014',
    startdate: '15/05/2022',
    departement: 'tokyo',
    street: 'rue des inventeurs',
    city: 'San Fransokyo',
    state: 'SC',
    zipcode: '65321',
  },
]
