export const employeesList = [
  {
    firstname: 'Flash',
    lastname: 'McQueen',
    dateOfBirth: '14/03/2006',
    startdate: '14/06/2006',
    departement: 'Les Bagnoles',
    street: 'route 66',
    city: 'Radiator Springs',
    state: 'AL',
    zipcode: '34567',
  },
  {
    firstname: 'Buzz',
    lastname: 'Lightyear',
    dateOfBirth: '22/11/1995',
    startdate: '24/01/2022',
    departement: 'Planete inconnu',
    street: 'route des étoiles',
    city: 'Vers l infini et au-delà',
    state: 'AZ',
    zipcode: '57421',
  },
  {
    firstname: 'Robert',
    lastname: 'Parr',
    dateOfBirth: '05/11/2004',
    startdate: '12/04/2017',
    departement: 'ville des super-heros',
    street: 'rue des indestructibles',
    city: 'Metroville',
    state: 'AR',
    zipcode: '76524',
  },
  {
    firstname: 'Remy',
    lastname: 'Ratatouille',
    dateOfBirth: '29/06/2017',
    startdate: '07/07/2020',
    departement: 'Paris',
    street: 'rue Auguste Gusteau',
    city: 'Paris',
    state: 'CO',
    zipcode: '75000',
  },
  {
    firstname: 'Baymax',
    lastname: 'Baymax',
    dateOfBirth: '07/11/2014',
    startdate: '15/05/2022',
    departement: 'tokyo',
    street: 'les nouveaux heros',
    city: 'San Fransokyo',
    state: 'SC',
    zipcode: '65321',
  },
  {
    firstname: 'Spot',
    lastname: 'DeCromagnon',
    dateOfBirth: '25/11/2015',
    startdate: '15/01/2022',
    departement: 'DansLANature',
    street: 'Entre2Grottes',
    city: 'La Vallée d Arlo',
    state: 'OR',
    zipcode: '78452',
  },
  {
    firstname: 'Nick',
    lastname: 'Wilde',
    dateOfBirth: '04/03/2016',
    startdate: '04/03/2021',
    departement: 'Downtown',
    street: 'Place du sahara',
    city: 'Zootopie',
    state: 'RI',
    zipcode: '32154',
  },
  {
    firstname: 'Nemo',
    lastname: 'Sushi',
    dateOfBirth: '26/11/2003',
    startdate: '26/11/2003',
    departement: 'Grande barriere de corail',
    street: 'Sherman 42',
    city: 'Sydney',
    state: 'SC',
    zipcode: '52314',
  },
  {
    firstname: 'Vaiana',
    lastname: 'Moana',
    dateOfBirth: '30/11/2016',
    startdate: '05/10/2018',
    departement: 'île du Pacifique',
    street: 'Motunui',
    city: 'île de Motunui',
    state: 'RI',
    zipcode: '36254',
  },
  {
    firstname: 'Wall_E',
    lastname: 'Compacteur terrien',
    dateOfBirth: '30/07/2008',
    startdate: '05/10/2045',
    departement: 'Espace',
    street: 'allée centrale',
    city: 'Vaisseau spatial Axiom',
    state: 'SD',
    zipcode: '98657',
  },
  {
    firstname: 'Bob',
    lastname: 'Razowski',
    dateOfBirth: '28/10/2001',
    startdate: '04/09/2015',
    departement: 'Monstre et Cie',
    street: 'rue bizarre',
    city: 'Monstropolis',
    state: 'MP',
    zipcode: '56384',
  },
  {
    firstname: 'Dracula',
    lastname: 'comte',
    dateOfBirth: '13/02/2001',
    startdate: '13/03/1966',
    departement: 'Transylvanie',
    street: 'rue risquée',
    city: 'Hotel Transylvania',
    state: 'HI',
    zipcode: '45632',
  },
  {
    firstname: 'Manny',
    lastname: 'mammouth',
    dateOfBirth: '26/06/2002',
    startdate: '18/01/2012',
    departement: 'ère glaciaire',
    street: 'à coté de Sid',
    city: 'préhistorique',
    state: 'GA',
    zipcode: '75315',
  },
  {
    firstname: 'Alex',
    lastname: 'le lion',
    dateOfBirth: '22/05/2005',
    startdate: '23/04/2010',
    departement: 'Manhattan',
    street: 'zoo de Central Park',
    city: 'New-york',
    state: 'MA',
    zipcode: '23541',
  },
  {
    firstname: 'Eep',
    lastname: 'Croods',
    dateOfBirth: '03/07/2013',
    startdate: '05/09/2016',
    departement: 'ère Croodéolithique',
    street: 'Mère Nature',
    city: 'Grotte des Croods',
    state: 'GU',
    zipcode: '02024',
  },
  {
    firstname: 'Carl',
    lastname: 'Fredricksen',
    dateOfBirth: '13/05/2009',
    startdate: '05/02/2013',
    departement: 'Mont Roraima',
    street: 'Chute du paradis',
    city: 'Salto Angel',
    state: 'SC',
    zipcode: '23142',
  },
  {
    firstname: 'Volt',
    lastname: 'Star malgré lui',
    dateOfBirth: '03/12/2008',
    startdate: '03/02/2012',
    departement: 'Californie',
    street: 'studio d enregistrement',
    city: 'Hollywood',
    state: 'LA',
    zipcode: '63482',
  },
  {
    firstname: 'Mary',
    lastname: 'Katherine',
    dateOfBirth: '05/06/2013',
    startdate: '14/01/2018',
    departement: 'Epic',
    street: 'La bataille du royaume secret',
    city: 'Monde des hommes feuilles',
    state: 'MH',
    zipcode: '00023',
  },
  {
    firstname: 'Tristesse',
    lastname: 'Triste',
    dateOfBirth: '17/06/2015',
    startdate: '10/11/2017',
    departement: 'Quartier général',
    street: 'entre2neuronnes',
    city: 'Tête de Riley',
    state: 'TX',
    zipcode: '01010',
  },
  {
    firstname: 'Blu',
    lastname: 'Perroquet bleu',
    dateOfBirth: '13/04/2011',
    startdate: '19/10/2012',
    departement: 'Rio',
    street: 'merveilles exotiques',
    city: 'Rio de janeiro',
    state: 'PR',
    zipcode: '01010',
  },
]
